name: 🐞 Bug
description: File a bug report
title: "[BUG] <title>"
labels: ["bug", "documentation", "cicd", "ui", "enhancement"]
projects: ["Shoes Project"]
assignees:
  - kirubeltadesse
  - roberamelaek
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true
  - type: input
    id: bun
    attributes:
      label: bun Version
      description: "Please provide the full bun version of your project."
      placeholder: "v1.0.3"
    validations:
      required: true
  - type: dropdown
    id: location
    attributes:
      label: Project Location
      description: How are you running the project?
      options:
        - Local
        - Inside Docker Container
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
